apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: whoami
          image: iansegers/whoami:v1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 600m
              memory: 1Gi
          ports:
            - containerPort: 3000
              name: whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: backend
  type: ClusterIP