apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: backend
          image: iansegers/poc-microservice:v1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 600m
              memory: 1Gi
          ports:
            - containerPort: 3000
              name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: frontend
          image: iansegers/poc-web-api:v2
          env:
            - name: SOURCE_URL
              value: "http://backend.default.svc.cluster.local:3000/"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 600m
              memory: 1Gi
          ports:
            - containerPort: 3000
              name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
  selector:
    app: frontend
  type: LoadBalancer