apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: whoami
          image: iansegers/whoami:v1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 600Mi
          ports:
            - containerPort: 3000
              name: whoami-port
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: whoami-port
  selector:
    app: whoami
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami-ingress
  labels:
    app: whoami
    tier: public
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: whoami.mymusic.zone
      http:
        paths:
          - backend:
              serviceName: whoami
              servicePort: 80